### PR TITLE
Use filewatcher to look for JS file updates

### PR DESCRIPTION
**Pull request by dkRasLar**
To accommodate compiling TS to JS, and having that automatically be uploaded, I use a filewatcher to trigger uploading the new file. When changing a JS file directly the file is sent twice currently. Which means this **isn't done** yet.

Putting it here to hopefully get some feedback.

### CODE REVIEW

**Comment by arnoudkooi** [comment]
Couldn't you capture the .ts file save, do the compiling and save and upload the .js?

**Comment by dkRasLar** [comment]
The problem is that you're then assuming control of the TypeScript compilation process. You might be able to do execute the default build task, but this assumes there's even one there.

Another option is to simply move everything to using file watchers. This would also enable support for using a templating engine for HTML or a CSS preprocessor. Though it does require a big-ish (relatively) rewrite of the uploading routine.

Note, I'm not looking at all at using this for Widgets, so maybe those have their own set of requirements?

**Comment by arnoudkooi** [comment]
Would you still be interested to implement this?

**Comment by arnoudkooi** [comment]
If you still want to implement, please get in touch. Closing this as it is behind master.

**Pull request closed without merging**
